[package]
name = "text_based_search"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
actix-web-lab = "0.19.1"
serde = "1.0.189"
serde_json = "1.0.107"
